### PR TITLE
Add EDD 3.0 compatibility

### LINKED ISSUE #15: EDD 3.0 compatibility

### PR DESCRIPTION
**Pull request by ashleyfae**
Closes #15

### CODE REVIEW

**Review by robincornett — APPROVED** [review]
Tested in 3.0 and 2.10 and both are working as expected.

My only suggestion is a minor one and it would be to use `share-alt` or something instead of `chart-area` for the report icon, but that may be because I have Recurring and SL active as well--in that case I'm seeing `chart-area` four times and it would be nice to have a little differentiation.

**Comment by ashleyfae** [comment]
Good idea.

**Review by dimadin — COMMENTED** [review]
@ashleyfae Could you please tell me why `function_exists( 'edd_get_orders' )` check is preferred?

**Comment by ashleyfae** [comment]
> @ashleyfae Could you please tell me why `function_exists( 'edd_get_orders' )` check is preferred?

Just because checking for `3.0` doesn't work with our beta versions. It will fail if you're on `3.0-beta1`. And rather than hard-coding in a specific beta version, the function check just feels a little easier. :shrug:

**Review by LisaCee — APPROVED** [review]

**Pull request merged**
